import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Navigation } from './components/navigation/navigation'

import { PropsWithChildren } from "react";

export const Layout = ({children}:PropsWithChildren) => {
  return (
    <div>

       <Navigation/>
      {children}
    </div>
  );
}

export default Layout;
// const inter = Inter({ subsets: ['latin'] })

//  export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">

//       <body className={inter.className}>
        
//       <Navigation/>
//         {children}
        
//       </body>
//     </html>
//   )
// }
